# Generated by Django 4.1.1 on 2022-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_hidden_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
